import { useMutation } from '@tanstack/react-query';
import {
  generateSubtasks,
  generateDescription,
  suggestTags,
} from '../api/aiApi';

import { message } from 'antd';
import type { ITag } from '../types';

interface AiAssistantCallbacks {
  onSubtaskSuccess: (subtasks: string[]) => void;
  onDescriptionSuccess: (description: string) => void;
  onTagSuccess: (tags: ITag[]) => void;
}

export const useAiAssistant = ({
  onSubtaskSuccess,
  onDescriptionSuccess,
  onTagSuccess,
}: AiAssistantCallbacks) => {

  const { mutate: generateSubtasksMutate, isPending: isSubtaskLoading } =
    useMutation({
      mutationFn: generateSubtasks,
      onSuccess: (subtasks) => {
        message.success(`${subtasks.length} sub-tasks generated by AI!`);
        onSubtaskSuccess(subtasks); // Başarı durumunda 'TaskModal'daki fonksiyonu çağır
      },
      onError: (err) => message.error(`AI Subtask failed: ${err.message}`),
    });

  const { mutate: generateDescriptionMutate, isPending: isDescriptionLoading } =
    useMutation({
      mutationFn: generateDescription,
      onSuccess: (data) => {
        message.success('Description generated by AI!');
        onDescriptionSuccess(data.description); // Başarı durumunda 'TaskModal'daki fonksiyonu çağır
      },
      onError: (err) => message.error(`AI Description failed: ${err.message}`),
    });

  const { mutate: suggestTagsMutate, isPending: isTagLoading } = useMutation({
    mutationFn: suggestTags,
    onSuccess: (suggestedTags) => {
      if (suggestedTags.length === 0) {
        message.info('AI found no matching tags.');
        return;
      }
      message.success('AI suggested tags!');
      onTagSuccess(suggestedTags); 
    },
    onError: (err) => message.error(`AI Tag suggestion failed: ${err.message}`),
  });

  return {
    generateSubtasks: generateSubtasksMutate,
    isSubtaskLoading,
    generateDescription: generateDescriptionMutate,
    isDescriptionLoading,
    suggestTags: suggestTagsMutate,
    isTagLoading,
  };
};